name: newstaff
version: '${version}'
main: pt.z4.newstaff.Newstaff
commands:
  nstaff:
    description: Join/Leave on the staff mode
    permission: newstaff.use
    aliases: [staff]
  staffchat:
    description: Send a message to the staff chat
    permission: newstaff.staffchat
    aliases: [sc]